### ISSUE TITLE
BASIC TI$ should use clock_get_date_time/clock_set_date_time

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#113]
Classic KERNAL has the `RDTIM`/`SETTIM` calls, which accesses a timer that updates 60 times a second and resets to after after 24*60*60*60 ticks, i.e. after 24h.

The X16 KERNAL has changed `RDTIM`/`SETTIM` to have a 24 bit timer that doesn't reset after 24h, and has added the calls `clock_get_date_time`/`clock_set_date_time`, which access a 24h real-time-clock. (It's currently implemented in software, but it may be bridged to RTC hardware later.)

BASIC currently uses `RDTIM`/`SETTIM` for both TI and TI$, like the original BASIC V2.

Instead:
* TI$ should use `clock_get_date_time`/`clock_set_date_time` instead. It won't have to convert between a jiffies offset and hh:mm:ss any more, making the code much simpler. (We can also get rid of the special-case FBLIB function `foutim` (C64 address: $BE68) then!)
* TI should continue to use `RDTIM`/`SETTIM`, i.e. remain unchanged. TI and TI$ will no longer be connected. TI$ will now be the wall-clock *time*, and TI will be a *timer*.

**Comment by EgonOlsen71** [comment]
As usual, I dislike breaking semantics that people are used to for decades for no apparent (when viewed from the perspective of a BASIC coder) reason. In this case, I don't get how to set/reset the time(r). Now, you can do TI$="000000" to reset both. If I got this correctly, I assume that you can't reset TI anymore with this change!?

**Comment by mist64** [comment]
You can reset TI by assigning `TI=0`.

I doubt a lot of people rely on TI and TI$ being connected.

**Comment by EgonOlsen71** [comment]
Well, everybody who uses TI relies on this until now, because the way to reset it is via TI$. I'm not saying that this is a good or logical thing. I'm just not sure that it's worth it to break compatibility at this point. So far, existing BASIC commands, variables and functions behave the same between the original Cxx BASIC and this version as far as I can see it (apart from new keywords not being usable as variable names anymore of course). This change would break with that.

**Comment by mist64** [comment]
In my philosophy, compatibility is a worthwhile goal, but bug-for-bug compatibility is not. The fact that TI and TI$ are connected and that TI can't be reset directly does not seem like conscious design decisions, but as a pragmatic way to simplify the code – I'd call it a quirk.

On more modern Microsoft-style BASIC implementations, like GWBASIC and QBASIC, TIME$ is in fact connected to the real-time-clock and not meant for timing code, but to access the wall clock time.

That's why I'd like to see TI$ as the real-time-clock, and TI can still be used for timing code.

I'd consider going for compatibility of there is a lot of code relying on a certain behavior. But I don't think this is the case here.

**Comment by BruceMcF** [comment]
It's definitely something people use if they are profiling on the C64, because that's how you do it ...but I don't know how many Basic programs rely on that, or whether it's just people who were writing those programs relied on it, as a system tool.

The most direct solution that maintained compatibility while providing a substantial feature upgrade would be to raise the Basic variable name limit to 4 characters and have TIME$, distinct from TI$ (which could be documented as an abbreviation for Timer$). The allowed variable name length would be an almost perfect example of upward compatibility.

**Comment by mist64** [comment]
Implemented in ca2d74c.
