### ISSUE TITLE
Inconsistent joystick information

### ISSUE THREAD

**Issue by joolin1** [commanderx16/x16-rom#131]
joystick_get returns the following information:

        byte 0:        | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
                  NES  | A | B |SEL|STA|UP |DN |LT |RT |
                  SNES | B | Y |SEL|STA|UP |DN |LT |RT |

        byte 1:        | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
                  NES  | 0 | 0 | 0 | 0 | 0 | 0 | 0 | X |
                  SNES | A | X | L | R | 1 | 1 | 1 | 1 |

I would be easier to for developers if the layout for byte 0 was the same regardless of type of controller (NES or SNES). In other words like this:

        byte 0:        | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
                  NES  | A | B |SEL|STA|UP |DN |LT |RT |
                  SNES | A | B |SEL|STA|UP |DN |LT |RT |

        byte 1:        | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
                  NES  | 0 | 0 | 0 | 0 | 0 | 0 | 0 | X |
                  SNES | X | Y | L | R | 1 | 1 | 1 | 1 |

**Comment by BruceMcF** [comment]
I don't mind having the raw information: it's faster and smaller in the Kernel and if I am remapping SNES to NES, I would use mask flags and let the remapping be user-settable anyway, so the extra work to put A/B would be wasted. But the remapping would work either way:

``
S2NES:
    STZ button
    LDA joy
    AND maskB0 ; %BY000000
    STA button+1
    LDA joy+1
    AND maskB1 ; %AXLR0000
    ORA button+1
    CLC
    BNE +
    SEC
+  ROL button
    LDA joy
    AND maskA0 ; %BY000000
    STA button+1
    LDA joy+1
    AND maskA1 ; %AXLR0000
    ORA button+1
    CLC
    BNE +
    SEC
+  ROL button
    LDA joy0
    AND #%11111100
    ORA button
    STA joy0
    STZ joy1
    RTS
``
My default would map %01000000:%10100000 for A and %10000000:%01010000 for B.

**Comment by joolin1** [comment]
How thick the layer against hardware should be is always a relevant question. My thought was that everyone would be happy with a consequent layout for byte 0. Otherwise just about every game developer would have to write their own wrapper function for _joystick_get_ to handle different uses of controllers. Therefore it would be better to put the code in the kernel for everyone to benefit from. 
I don't really see why you would want to remap the raw information in any other way. But you might have a good point, I am not all experienced in this.

**Comment by BruceMcF** [comment]
If it's a pinball game, I'd prefer that the type flipper inputs be on the triggers.
If it's a racing game, if A is the gas and B is the brake, I like to have A and B be A and the left trigger be the brake.
When I play Galaxian on my DS-lite, which only has left, right and fire (and not machine gun bullet fire, but missile fire, where you can't fire again until it has exploded or gone off screen), I like to use B at the bottom of the diamond as the fire button.

SNES controllers are better if you want more than two buttons ... because they have them. They are also better if you only want two buttons ... because they give you flexibility exactly which two you get to use.

**Comment by rossato** [comment]
Although mapping B, A to B, A might make more sense literally, it feels very different on the two controllers.  Try playing NInja Gaiden Trilogy on SNES to see how awkward it is.  Y, B to B, A is a more natural feeling mapping: your thumb-tip is on the "action" button and able to rock onto the "jump" button.  8bitdo uses this mapping for their SNES controllers on an NES receiver.

**Comment by mist64** [comment]
As we are getting closer and closer to the final spec and the final board, it seems we're converging on two SNES controller ports at the back of the X16:

https://www.commanderx16.com/forum/index.php?/topic/210-commander-x16-second-prototype-pcbs-are-here/

It probably makes most sense to remove all documentation on NES controllers. The code never cared either way, it just speaks the LATCH/CLK/DATA protocol, which is identical across NES and SNES controllers.

**Comment by BruceMcF** [comment]
> It probably makes most sense to remove all documentation on NES controllers. The code never cared either way, it just speaks the LATCH/CLK/DATA protocol, which is identical across NES and SNES controllers.

This would tie in with my Joy(0) issue, which would give SNES inputs from the keyboard for all 12 buttons ... since $xF and $x0 just physically ARE the ID nybbles for SNES and NES controllers, $x1 as the ID nybble for the joystick still makes sense.

But the NES could be moved out of the main documentation into a footnote{*}
{*Note: if using an NES controller with a port adapter, A will be interpreted as the SNES B button, and B will be interpreted as the SNES Y button. Game authors who wish to make a modified control scheme available for NES game controllers connected through a port adapter may note that byte 1 for an NES controller will be all bits clear, while the SNES will always return the lower four bits of bit 1 set,}

**Comment by greg-king5** [comment]
A NES controller can be plugged in.  Therefore, it should be documented.  (The programmer's guide shouldn't care _how_ the controllers must be plugged.)

I prefer that the document stay the way that it currently is.  It's much easier to understand than a wordy footnote.

**Comment by BruceMcF** [comment]
Lots of things can be plugged in with a suitable adapter. The SNES controllers would be the ones that ship with a full system, so that's what the main table should document, along with the Keyboard back-up if no controller is plugged in.

But put a shift register in a dongle with a DB9, you can read an Atari Joystick  & Sega Master system two button gamepad: P1->d3, P2->d2, P3->d1, P4->d0, P6->d7, P9->d6. The only difference with the SNES gamepad is the shift register is already included so it only needs the ungainly large NES connector for a wire-through adapter.

But, yes, the footnote should probably include the chart instead of the verbiage:
{*Note: if using an NES controller with a port adapter, use the following chart:
    NES            | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
    byte 0:        | A | B |SEL|STA|UP |DN |LT |RT |
    byte 1:        | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

A game that wants to support sub-SNES controllers that has detected an ID nybble of #0 could message:
1] For an NES controller, press Start.
2] For a Master System controller, press B.
3] For an Atari Joystick, press Fire.

But anything controller dongle that needs a microcontroller like an AVR8 to read the gamepad ... Sega Arcade Pad, PS4, XBox1 ... the microcontroller ought to mimic an SNES gamepad and the SNES ID.

**Comment by mist64** [comment]
The final hardware will only support SNES controllers, not NES ones, so all NES features and documentation will be removed.
