### ISSUE TITLE
Using COLOR in mode $80 cause a lockup

### ISSUE THREAD

**Issue by dlvogel** [commanderx16/x16-rom#153]
It appears when in mode $80 and using the SCREEN command with COLOR causes the system to lockup.

Example program:

10 SCREEN $80
20 COLOR 0,1
30 PRINT "A"

This works fine in mode $02

**Comment by mist64** [comment]
Confirmed this hangs:

`SCREEN $80: COLOR 0,1`

**Comment by mist64** [comment]
This also reproduces it:

`SCREEN $80: PRINTCHR$(5)`

5 is the PETSCII control code for "white".

**Comment by mist64** [comment]
Ugh, that's what I get for not working on this project for months! It's so obvious now! ;-)

`COLOR 0,1` normally sets black text on a white background. In mode $80, color 0, which is normally black, is now translucent. So you're setting text to translucent on white. :(

There is currently no way to have black text in mode $80, because it's a 16 color mode that's down to 15 colors because of translucency. What you could do is change the palette and sacrifice another color.

I'll add a note in the docs.

**Comment by mist64** [comment]
https://github.com/commanderx16/x16-docs/commit/cdc2009cd24f8e4009c2c9f1966e236939f3df7e

**Comment by greg-king5** [comment]
Run that program.  Then, hold down the `Ctrl` key while you type the `3` key (the cursor will change to the red color).  Move the cursor up three lines.  You will see the letter `A` (while the cursor is blinking over it).

**Comment by greg-king5** [comment]
By the way, on a white screen, the gray colors 11 and 12 look better than black.  Their contrast is "nicer".
