### ISSUE TITLE
Mouse scaling is not applied when changing screen modes

### ISSUE THREAD

**Issue by MCPEmaniac** [commanderx16/x16-rom#160]
I'm having problems with the mouse in 40x30 text mode in my C application.

First when using a scale of 2 for a 320x240 screen the mouse position is reported in the ranges 0<=y<640 and 0<=x<480 instead of 0<=y<320 and 0<=x<240 which I would expect.

Second at times I can't seem to move the mouse to certain portions of the screen. This occurs somewhat randomly and the inaccessible portion of the screen also seems somewhat random. I've noticed this in other applications posted to the download page of the official Commander X16 website as well as my own application. I noticed this problem can sometimes be solved by moving the mouse all the way the left, right, top, and bottom sides of the entire monitor screen and then moving the mouse back inside of the emulator window.

**Comment by mist64** [comment]
The second problem you describe is a limitation of the emulator: https://github.com/commanderx16/x16-emulator/issues/376

**Comment by mist64** [comment]
Confirmed the first problem. The `mouse_config` API allows setting the mouse scale to 1x, 2x or leave it the same. The `MOUSE` BASIC instruction always passes 0, which means leave the scale the same. Consequently, no matter what the screen mode is, the mouse scale will always stay the same, i.e. usually at the default 1x, so you get coordinates in the range of 0-639, 0-479.

Even if the scale was set to 2x, it would not account for the missing 40 pixel lines in mode 128 (320x200 graphics).

**Comment by mist64** [comment]
Instead of the scale, the KERNAL should allow setting the size of the screen. In order for the numbers to fit into registers, the size should be given in 8px increments, so for the 80x30 text screen, the mouse region would be 80x30, and for the 320x200 graphics screen, it would be 40x25, for example. It is always assumed that the mouse region matches the screen size (restricting the mouse in a smaller rectangle is not supported), so the KERNAL can deduct from a width <= 320 that a scale of 2 should be used.
