### ISSUE TITLE
FB_set_pixels crashes when count > 255

### ISSUE THREAD

**Issue by irmen** [commanderx16/x16-rom#179]
FB_set_pixels with a count of 256 or more crashes.
I think it's caused by the jsr that it's doing internally and that it is not properly dealing with the double loop invocation or some thing.

What confuses me is that FB_set_pixels is defined twice:

https://github.com/commanderx16/x16-rom/blob/a853afd4ff164f4b9b63762bf6e9f1931e6683f8/kernal/drivers/x16/framebuffer.s#L176
and also here
https://github.com/commanderx16/x16-rom/blob/31a9470eb75ae2e5c0fd3ff9617a78491e7df024/kernal/graph/drv_ram.s#L164

**Comment by greg-king5** [comment]
> What confuses me is that `FB_set_pixels:` is defined twice:

https://github.com/commanderx16/x16-rom/blob/31a9470eb75ae2e5c0fd3ff9617a78491e7df024/kernal/graph/drv_ram.s#L6
Ignore that file.

**Comment by greg-king5** [comment]
> `FB_set_pixels` with a count of 256 or more crashes.

It's caused by the `PopB` lines in the inner loop -- that's the wrong place.  When the count's high-byte is non-zero, they "eat" the stack!  The pseudo-registers must be handled in the same way that `FB_get_pixels` does it: https://github.com/commanderx16/x16-rom/blob/9498437e4baf39b75a36b158f98f0ef9a59b4978/kernal/drivers/x16/framebuffer.s#L208-L214.

**Comment by irmen** [comment]
That looks like something I can attempt to make a fix and a PR for later this week or in the weekend perhaps.
