### ISSUE TITLE
$ and % prefixes don't work for DATA entries

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-rom#2]

**Comment by mist64** [comment]
`READ` goes through a different code path than expression evaluation. Like `INPUT`, it calls `FIN` (C64: $BCF3), which can only handle decimal floats/ints. Support for $/% has to be added to this codepath separately.

**Comment by paulscottrobson** [comment]
There is also the unquoted text in DATA issue. $44 as READ data can be read, it just thinks it is a string (so READ A$ works). I would think the READ code has a check for the first character being numeric (- . 0-9) and if it isn't, it treats it as string data. This introduces potentially a back incompatibility because adding $% would break programs that use data beginning with such as strings (though not many of these !)
