### ISSUE TITLE
recent change made joysticks no longer work

### ISSUE THREAD

**Issue by irmen** [commanderx16/x16-rom#200]
The changes made in this commit a few days ago d2b137bf3a1d2c5afe57f25346f007986a502c05 killed the joysticks.
Running the new emulator with ROMs built without this change, still work.

test program in BASIC i'm using:

10?JOY(1):GOTO 10

the values don't change anymore since this commit above.
(SDL still picks up the controller as shown by the debug messages printed on the console)

**Comment by indigodarkwolf** [comment]
Looks like the return value in the accumulator for joystick_get() is getting lost because the macro specifically stores it at the start of the function and then retrieves it at the end of the function. So that needs to change to only preserve the value of the accumulator at the end of the function. 

Possibly replace the macro at the start with `KVARS_START_TRASH_A_NZ`, then change the end of the function to stow A to kvswitch_tmp1, do `KVARS_END_TRASH_A_NZ`, then retrieve A from kvswitch_tmp1 before the `rts`?

**Comment by indigodarkwolf** [comment]
Ah, well, I had the right idea, but the fix had to be slightly different. PR incoming.

**Comment by irmen** [comment]
above PR was merged and solved this issue.
