### ISSUE TITLE
running PSET x,y,color while in text mode crashes BASIC into the monitor

### ISSUE THREAD

**Issue by mooinglemur** [commanderx16/x16-rom#342]
Minimal case:

At the READY prompt:
`PSET 0,0,0`

which immediately enters the machine language monitor.

**Comment by mooinglemur** [comment]
This also affects other drawing commands such as RECT and LINE

more appropriate outcomes could be

- no-op, silent failure
- enter graphics mode and apply the drawing command
- return an error such as `?ILLEGAL QUANTITY` or perhaps `?DEVICE NOT PRESENT`

**Comment by mooinglemur** [comment]
happens in R40 and R41, unsure about current master particularly after the graph bank move.

**Comment by Jaxartes** [comment]
I can confirm that this happens with the latest ROM code, which includes commit dd6623727b1fa846. It also happens with other graphics commands, such as "RECT0,0,100,100,100" or "LINE0,0,100,100,100".

The cause of the problem is that the graphics driver isn't initialized until you switch to graphics mode. If you switch to graphics mode then back to text mode then these commands won't crash, they just don't do anything visible. 

Some thoughts on coding a fix in ROM, if this "no-op, silent failure" behavior is desired:

1. Tried, doesn't work great: I tried modifying 'screen_mode' so as to initialize the graphics driver (through 'GRAPH_init') when entering text mode, too, and not just graphics mode. It worked, but also forced text mode to 40x30 which is bad.
2. Works, simple, feels a little lame: Modify the kernal's screen initialization ('cint') where it sets mode 0, to set mode 128 first. In my testing this seems to solve the problem. It might produce a brief video glitch on startup and reset but that may be acceptable (and consistent with some historic 8 bit systems).
3. Haven't tried: Create a "dummy" graphics driver which implements the same API as frambebuffer.s but doesn't do anything.

**Comment by mist64** [comment]
> * no-op, silent failure

Not very user-friendly.

> * enter graphics mode and apply the drawing command

There are several modes, which one?

> * return an error such as `?ILLEGAL QUANTITY` or perhaps `?DEVICE NOT PRESENT`

I like this one. But we probably want a new error. The C128 prints `?NO GRAPHICS AREA ERROR`; I think we need better wording. `?NO GRAPHICS MODE` maybe?

**Comment by Jaxartes** [comment]
New pull request https://github.com/commanderx16/x16-rom/pull/351 replacing the old one, to fix this by making an error.
