### ISSUE TITLE
Screen editor changes colors when deleting across line boundary

### ISSUE THREAD

**Issue by markjreed** [commanderx16/x16-rom#353]
Reproduce:

SCREEN $80
10 PRINT "THIS IS A VERY LONG LINE THAT WILL WRAP IN 40-COLUMN MODE"
LIST

Cursor up to the first column after the wrap (the "W" in "WRAP") and press DELETE. When the text slides around the corner and in to the right side of the line above, it will be white text on dark blue instead of light blue on whtie.

Demo: https://cdn.discordapp.com/attachments/629903630916648962/1035640186228453516/bug.gif

**Comment by jestin** [comment]
I'm fairly certain the code that causes this issue is here: https://github.com/commanderx16/x16-rom/blob/master/kernal/cbm/editor.s#L591

Somehow `screen_get_color` is returning the wrong value.

**Comment by jestin** [comment]
I suspect the issue is that the color is being obtained from the hidden area of the screen.  I see no logic in the code that accounts for `pntcol` being in an area hidden by dchscale.

https://cdn.discordapp.com/attachments/629903630916648962/1035650608725774386/unknown.png

**Comment by jestin** [comment]
I believe the problem is that `screen_get_color` and `screen_set_color` don't take into account modes whose text wrap before the full width of the screen.  Since `screen_get_char` and `screen_set_char` _do_ take this into account, I just added a few lines that do what they are doing.  So far as I can tell this works without creating other issues.

Here's the PR: https://github.com/commanderx16/x16-rom/pull/354
