### ISSUE TITLE
HEX$(), BIN$() as counterparts to $A000 and %11001100

### ISSUE THREAD

**Issue by tomxp411** [commanderx16/x16-rom#49]
As suggested here:

https://murray2.com/threads/suggestion-for-additional-basic-commands.328/post-2010

We have the $ prefix for hexadecimal numbers and the % prefix for binary numbers. We should have HEX$() and BIN$() functions to print numbers out in hex or binary format.

**Comment by mist64** [comment]
Sounds great. Should be easy. :)

**Comment by JimmyDansbo** [comment]
I have been trying to create the HEX$() function, but I can not seem to get my head around how to actually add the command to BASIC.
So far, this is what I have done:
* Created function in x16additions.s, called hexd (I see that chr$, str$ and so on are named like that)
* Added '.word hexd' in tokens.s in the stmdsp2 list under '.word joy'
* Added '.byt "HEX", '$' + $80' in token2.s in the reslst2 list under '"byt "JO", 'Y' + $80'
* Changed num_esc_functions from 5 to 6

Still it seems that BASIC does not recognize the new keyword, can someone point me in the direction of what I am missing?

**Comment by JimmyDansbo** [comment]
So, I managed to get HEX$ recognized as a command/token.
Instead of .byt "HEX", '$' + $80 I had to do .byt "HEX", $a4
It seems that '$'+$80 is not correct, probably because ascii value of '$' is not the same as the petscii value.

Now I need help figuring out how to return a string from my function. Looking at existing functions have not gotten me on the correct track yet. :(

**Comment by greg-king5** [comment]
> Instead of `.byt "HEX", '$' + $80`, I had to do `.byt "HEX", $a4`.
> It seems that `'$'+$80` is not correct, probably because ascii value of '$' is not the same as the petscii value.

That is strange.  `'$'+$80` is `$a4`, in both ASCII and PetSCII.
